logdir: logs/20200502-114730/
test_episode: 1000

env_params:
  state_mode: 'feature'

replay_memory:
  capacity: 10000

fit_params:
  batch_size: 128
  episodes: 50000
  target_update: 100
  save_steps: 100
